version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /pkg/hub
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /pkg/hub/queue/drivers/sqs
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /web/inertia-demo/api
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
