services:
  app:
    image: ${GO_IMAGE:-golang:1.26.5-alpine}
    volumes:
      - .:/workspace
      - ./infra/.cache/go/path/bin:/go/bin
      - ./infra/.cache/go/mod:/go/pkg/mod
      - ./infra/.cache/go/build:/root/.cache/go-build
    working_dir: /workspace
