packages:
  - "web/docs"
  - "web/inertia-demo/app"
  - "web/inertia-demo/tests/e2e"
  - "sdk/console"
  - "sdk/container"
  - "sdk/httpx"
  - "sdk/money"
  - "sdk/tempo"
  - "sdk/tempo/tests"
  - "sdk/navigator-routes"
  - "sdk/workflow"
  - "infra"
  - "infra/*"

onlyBuiltDependencies:
  - esbuild

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
  cpu:
    - current
    - x64
    - arm64
