packages:
  - "apps/docs"
  - "apps/inertia/app"
  - "apps/inertia/tests/e2e"
  - "ts/console"
  - "ts/money"
  - "ts/tempo"
  - "ts/tempo/tests"
  - "ts/navigator-routes"
  - "ts/workflow"
  - "infra"
  - "infra/*"

onlyBuiltDependencies:
  - esbuild

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
  cpu:
    - current
    - x64
    - arm64
