packages:
  - "packages/console"
  - "packages/money"
  - "packages/tempo"
  - "packages/tempo/tests"
  - "packages/navigator-routes"
  - "packages/workflow"
  - "infra"
  - "infra/*"

onlyBuiltDependencies:
  - esbuild

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
  cpu:
    - current
    - x64
    - arm64
