export interface CurrencyDefinitionData {
	readonly decimal: string;
	readonly thousand: string;
	readonly code: CurrencyCode;
	readonly fraction: number;
	readonly numericCode: string;
	readonly grapheme: string;
	readonly template: string;
}

export interface CurrencySymbolData {
	readonly id: string;
	readonly currency: CurrencyCode;
}

export const CURRENCY_CODES = [
	'AED',
	'AFN',
	'ALL',
	'AMD',
	'ANG',
	'AOA',
	'ARS',
	'AUD',
	'AWG',
	'AZN',
	'BAM',
	'BBD',
	'BDT',
	'BGN',
	'BHD',
	'BIF',
	'BMD',
	'BND',
	'BOB',
	'BOV',
	'BRL',
	'BSD',
	'BTN',
	'BWP',
	'BYN',
	'BZD',
	'CAD',
	'CDF',
	'CHE',
	'CHF',
	'CHW',
	'CLF',
	'CLP',
	'CNY',
	'COP',
	'COU',
	'CRC',
	'CUC',
	'CUP',
	'CVE',
	'CZK',
	'DJF',
	'DKK',
	'DOP',
	'DZD',
	'EGP',
	'ERN',
	'ETB',
	'EUR',
	'FJD',
	'FKP',
	'GBP',
	'GEL',
	'GHS',
	'GIP',
	'GMD',
	'GNF',
	'GTQ',
	'GYD',
	'HKD',
	'HNL',
	'HTG',
	'HUF',
	'IDR',
	'ILS',
	'INR',
	'IQD',
	'IRR',
	'ISK',
	'JMD',
	'JOD',
	'JPY',
	'KES',
	'KGS',
	'KHR',
	'KMF',
	'KPW',
	'KRW',
	'KWD',
	'KYD',
	'KZT',
	'LAK',
	'LBP',
	'LKR',
	'LRD',
	'LSL',
	'LYD',
	'MAD',
	'MDL',
	'MGA',
	'MKD',
	'MMK',
	'MNT',
	'MOP',
	'MUR',
	'MRU',
	'MVR',
	'MWK',
	'MXN',
	'MXV',
	'MYR',
	'MZN',
	'NAD',
	'NGN',
	'NIO',
	'NOK',
	'NPR',
	'NZD',
	'OMR',
	'PAB',
	'PEN',
	'PGK',
	'PHP',
	'PKR',
	'PLN',
	'PYG',
	'QAR',
	'RON',
	'RSD',
	'RUB',
	'RWF',
	'SAR',
	'SBD',
	'SCR',
	'SDG',
	'SEK',
	'SGD',
	'SHP',
	'SLE',
	'SLL',
	'SOS',
	'SRD',
	'SSP',
	'STN',
	'SVC',
	'SYP',
	'SZL',
	'THB',
	'TJS',
	'TMT',
	'TND',
	'TOP',
	'TRY',
	'TTD',
	'TWD',
	'TZS',
	'UAH',
	'UGX',
	'USD',
	'USN',
	'UYI',
	'UYU',
	'UYW',
	'UZS',
	'VES',
	'VND',
	'VUV',
	'WST',
	'XAF',
	'XAG',
	'XAU',
	'XBA',
	'XBB',
	'XBC',
	'XBD',
	'XCD',
	'XDR',
	'XOF',
	'XPD',
	'XPF',
	'XPT',
	'XSU',
	'XTS',
	'XUA',
	'XXX',
	'YER',
	'ZAR',
	'ZMW',
	'ZWL',
] as const;

export type CurrencyCode = (typeof CURRENCY_CODES)[number];

export const CURRENCY_SYMBOLS = [
	{
		id: 'CFP',
		currency: 'XPF',
	},
	{
		id: 'NT$',
		currency: 'TWD',
	},
	{
		id: 'R$',
		currency: 'BRL',
	},
	{
		id: 'C$',
		currency: 'CAD',
	},
	{
		id: 'A$',
		currency: 'AUD',
	},
	{
		id: 'S$',
		currency: 'SGD',
	},
	{
		id: 'HK$',
		currency: 'HKD',
	},
	{
		id: '$',
		currency: 'USD',
	},
	{
		id: '€',
		currency: 'EUR',
	},
	{
		id: '£',
		currency: 'GBP',
	},
	{
		id: '¥',
		currency: 'JPY',
	},
	{
		id: '₹',
		currency: 'INR',
	},
	{
		id: '₣',
		currency: 'CHF',
	},
] as const satisfies readonly CurrencySymbolData[];

export const CURRENCY_DATA = {
	AED: { code: 'AED', decimal: '.', thousand: ',', fraction: 2, numericCode: '784', grapheme: '.د.إ', template: '1 $' },
	AFN: { code: 'AFN', decimal: '.', thousand: ',', fraction: 2, numericCode: '971', grapheme: '؋', template: '1 $' },
	ALL: { code: 'ALL', decimal: '.', thousand: ',', fraction: 2, numericCode: '008', grapheme: 'L', template: '$1' },
	AMD: { code: 'AMD', decimal: '.', thousand: ',', fraction: 2, numericCode: '051', grapheme: 'դր.', template: '1 $' },
	ANG: { code: 'ANG', decimal: ',', thousand: '.', fraction: 2, numericCode: '532', grapheme: 'ƒ', template: '$1' },
	AOA: { code: 'AOA', decimal: '.', thousand: ',', fraction: 2, numericCode: '973', grapheme: 'Kz', template: '1$' },
	ARS: { code: 'ARS', decimal: ',', thousand: '.', fraction: 2, numericCode: '032', grapheme: '$', template: '$1' },
	AUD: { code: 'AUD', decimal: '.', thousand: ',', fraction: 2, numericCode: '036', grapheme: 'A$', template: '$1' },
	AWG: { code: 'AWG', decimal: '.', thousand: ',', fraction: 2, numericCode: '533', grapheme: 'ƒ', template: '1$' },
	AZN: { code: 'AZN', decimal: '.', thousand: ',', fraction: 2, numericCode: '944', grapheme: '₼', template: '$1' },
	BAM: { code: 'BAM', decimal: '.', thousand: ',', fraction: 2, numericCode: '977', grapheme: 'KM', template: '$1' },
	BBD: { code: 'BBD', decimal: '.', thousand: ',', fraction: 2, numericCode: '052', grapheme: '$', template: '$1' },
	BDT: { code: 'BDT', decimal: '.', thousand: ',', fraction: 2, numericCode: '050', grapheme: '৳', template: '$1' },
	BGN: { code: 'BGN', decimal: '.', thousand: ',', fraction: 2, numericCode: '975', grapheme: 'лв', template: '$1' },
	BHD: { code: 'BHD', decimal: '.', thousand: ',', fraction: 3, numericCode: '048', grapheme: '.د.ب', template: '1 $' },
	BIF: { code: 'BIF', decimal: '.', thousand: ',', fraction: 0, numericCode: '108', grapheme: 'Fr', template: '1$' },
	BMD: { code: 'BMD', decimal: '.', thousand: ',', fraction: 2, numericCode: '060', grapheme: '$', template: '$1' },
	BND: { code: 'BND', decimal: '.', thousand: ',', fraction: 2, numericCode: '096', grapheme: '$', template: '$1' },
	BOB: { code: 'BOB', decimal: '.', thousand: ',', fraction: 2, numericCode: '068', grapheme: 'Bs.', template: '$1' },
	BOV: { code: 'BOV', decimal: '.', thousand: ',', fraction: 2, numericCode: '984', grapheme: 'BOV', template: '1 $' },
	BRL: { code: 'BRL', decimal: ',', thousand: '.', fraction: 2, numericCode: '986', grapheme: 'R$', template: '$1' },
	BSD: { code: 'BSD', decimal: '.', thousand: ',', fraction: 2, numericCode: '044', grapheme: '$', template: '$1' },
	BTN: { code: 'BTN', decimal: '.', thousand: ',', fraction: 2, numericCode: '064', grapheme: 'Nu.', template: '1$' },
	BWP: { code: 'BWP', decimal: '.', thousand: ',', fraction: 2, numericCode: '072', grapheme: 'P', template: '$1' },
	BYN: { code: 'BYN', decimal: ',', thousand: ' ', fraction: 2, numericCode: '933', grapheme: 'p.', template: '1 $' },
	BZD: { code: 'BZD', decimal: '.', thousand: ',', fraction: 2, numericCode: '084', grapheme: 'BZ$', template: '$1' },
	CAD: { code: 'CAD', decimal: '.', thousand: ',', fraction: 2, numericCode: '124', grapheme: '$', template: '$1' },
	CDF: { code: 'CDF', decimal: '.', thousand: ',', fraction: 2, numericCode: '976', grapheme: 'FC', template: '1$' },
	CHE: { code: 'CHE', decimal: '.', thousand: ',', fraction: 2, numericCode: '947', grapheme: 'CHE', template: '1 $' },
	CHF: { code: 'CHF', decimal: '.', thousand: ',', fraction: 2, numericCode: '756', grapheme: 'CHF', template: '1 $' },
	CHW: { code: 'CHW', decimal: '.', thousand: ',', fraction: 2, numericCode: '948', grapheme: 'CHW', template: '1 $' },
	CLF: { code: 'CLF', decimal: ',', thousand: '.', fraction: 4, numericCode: '990', grapheme: 'UF', template: '$1' },
	CLP: { code: 'CLP', decimal: ',', thousand: '.', fraction: 0, numericCode: '152', grapheme: '$', template: '$1' },
	CNY: { code: 'CNY', decimal: '.', thousand: ',', fraction: 2, numericCode: '156', grapheme: '元', template: '1 $' },
	COP: { code: 'COP', decimal: ',', thousand: '.', fraction: 2, numericCode: '170', grapheme: '$', template: '$1' },
	COU: { code: 'COU', decimal: '.', thousand: ',', fraction: 2, numericCode: '970', grapheme: 'COU', template: '1 $' },
	CRC: { code: 'CRC', decimal: '.', thousand: ',', fraction: 2, numericCode: '188', grapheme: '₡', template: '$1' },
	CUC: { code: 'CUC', decimal: '.', thousand: ',', fraction: 2, numericCode: '931', grapheme: '$', template: '1$' },
	CUP: { code: 'CUP', decimal: '.', thousand: ',', fraction: 2, numericCode: '192', grapheme: '$MN', template: '$1' },
	CVE: { code: 'CVE', decimal: '.', thousand: ',', fraction: 2, numericCode: '132', grapheme: '$', template: '1$' },
	CZK: { code: 'CZK', decimal: '.', thousand: ',', fraction: 2, numericCode: '203', grapheme: 'Kč', template: '1 $' },
	DJF: { code: 'DJF', decimal: '.', thousand: ',', fraction: 0, numericCode: '262', grapheme: 'Fdj', template: '1 $' },
	DKK: { code: 'DKK', decimal: ',', thousand: '.', fraction: 2, numericCode: '208', grapheme: 'kr', template: '$ 1' },
	DOP: { code: 'DOP', decimal: '.', thousand: ',', fraction: 2, numericCode: '214', grapheme: 'RD$', template: '$1' },
	DZD: { code: 'DZD', decimal: '.', thousand: ',', fraction: 2, numericCode: '012', grapheme: '.د.ج', template: '1 $' },
	EGP: { code: 'EGP', decimal: '.', thousand: ',', fraction: 2, numericCode: '818', grapheme: '£', template: '$1' },
	ERN: { code: 'ERN', decimal: '.', thousand: ',', fraction: 2, numericCode: '232', grapheme: 'Nfk', template: '1 $' },
	ETB: { code: 'ETB', decimal: '.', thousand: ',', fraction: 2, numericCode: '230', grapheme: 'Br', template: '1 $' },
	EUR: { code: 'EUR', decimal: '.', thousand: ',', fraction: 2, numericCode: '978', grapheme: '€', template: '$1' },
	FJD: { code: 'FJD', decimal: '.', thousand: ',', fraction: 2, numericCode: '242', grapheme: '$', template: '$1' },
	FKP: { code: 'FKP', decimal: '.', thousand: ',', fraction: 2, numericCode: '238', grapheme: '£', template: '$1' },
	GBP: { code: 'GBP', decimal: '.', thousand: ',', fraction: 2, numericCode: '826', grapheme: '£', template: '$1' },
	GEL: { code: 'GEL', decimal: '.', thousand: ',', fraction: 2, numericCode: '981', grapheme: 'ლ', template: '1 $' },
	GHS: { code: 'GHS', decimal: '.', thousand: ',', fraction: 2, numericCode: '936', grapheme: '₵', template: '$1' },
	GIP: { code: 'GIP', decimal: '.', thousand: ',', fraction: 2, numericCode: '292', grapheme: '£', template: '$1' },
	GMD: { code: 'GMD', decimal: '.', thousand: ',', fraction: 2, numericCode: '270', grapheme: 'D', template: '1 $' },
	GNF: { code: 'GNF', decimal: '.', thousand: ',', fraction: 0, numericCode: '324', grapheme: 'FG', template: '1 $' },
	GTQ: { code: 'GTQ', decimal: '.', thousand: ',', fraction: 2, numericCode: '320', grapheme: 'Q', template: '$1' },
	GYD: { code: 'GYD', decimal: '.', thousand: ',', fraction: 2, numericCode: '328', grapheme: '$', template: '$1' },
	HKD: { code: 'HKD', decimal: '.', thousand: ',', fraction: 2, numericCode: '344', grapheme: 'HK$', template: '$1' },
	HNL: { code: 'HNL', decimal: '.', thousand: ',', fraction: 2, numericCode: '340', grapheme: 'L', template: '$1' },
	HTG: { code: 'HTG', decimal: ',', thousand: '.', fraction: 2, numericCode: '332', grapheme: 'G', template: '1 $' },
	HUF: { code: 'HUF', decimal: ',', thousand: '.', fraction: 2, numericCode: '348', grapheme: 'Ft', template: '1 $' },
	IDR: { code: 'IDR', decimal: ',', thousand: '.', fraction: 2, numericCode: '360', grapheme: 'Rp', template: '$1' },
	ILS: { code: 'ILS', decimal: '.', thousand: ',', fraction: 2, numericCode: '376', grapheme: '₪', template: '$1' },
	INR: { code: 'INR', decimal: '.', thousand: ',', fraction: 2, numericCode: '356', grapheme: '₹', template: '$1' },
	IQD: { code: 'IQD', decimal: '.', thousand: ',', fraction: 3, numericCode: '368', grapheme: '.د.ع', template: '1 $' },
	IRR: { code: 'IRR', decimal: '.', thousand: ',', fraction: 2, numericCode: '364', grapheme: '﷼', template: '1 $' },
	ISK: { code: 'ISK', decimal: ',', thousand: '.', fraction: 0, numericCode: '352', grapheme: 'kr', template: '$1' },
	JMD: { code: 'JMD', decimal: '.', thousand: ',', fraction: 2, numericCode: '388', grapheme: 'J$', template: '$1' },
	JOD: { code: 'JOD', decimal: '.', thousand: ',', fraction: 3, numericCode: '400', grapheme: '.د.إ', template: '1 $' },
	JPY: { code: 'JPY', decimal: '.', thousand: ',', fraction: 0, numericCode: '392', grapheme: '¥', template: '$1' },
	KES: { code: 'KES', decimal: '.', thousand: ',', fraction: 2, numericCode: '404', grapheme: 'KSh', template: '$1' },
	KGS: { code: 'KGS', decimal: '.', thousand: ',', fraction: 2, numericCode: '417', grapheme: 'сом', template: '1 $' },
	KHR: { code: 'KHR', decimal: '.', thousand: ',', fraction: 2, numericCode: '116', grapheme: '៛', template: '$1' },
	KMF: { code: 'KMF', decimal: '.', thousand: ',', fraction: 0, numericCode: '174', grapheme: 'CF', template: '$1' },
	KPW: { code: 'KPW', decimal: '.', thousand: ',', fraction: 2, numericCode: '408', grapheme: '₩', template: '$1' },
	KRW: { code: 'KRW', decimal: '.', thousand: ',', fraction: 0, numericCode: '410', grapheme: '₩', template: '$1' },
	KWD: { code: 'KWD', decimal: '.', thousand: ',', fraction: 3, numericCode: '414', grapheme: '.د.ك', template: '1 $' },
	KYD: { code: 'KYD', decimal: '.', thousand: ',', fraction: 2, numericCode: '136', grapheme: '$', template: '$1' },
	KZT: { code: 'KZT', decimal: '.', thousand: ',', fraction: 2, numericCode: '398', grapheme: '₸', template: '$1' },
	LAK: { code: 'LAK', decimal: '.', thousand: ',', fraction: 2, numericCode: '418', grapheme: '₭', template: '$1' },
	LBP: { code: 'LBP', decimal: '.', thousand: ',', fraction: 2, numericCode: '422', grapheme: '£', template: '$1' },
	LKR: { code: 'LKR', decimal: '.', thousand: ',', fraction: 2, numericCode: '144', grapheme: '₨', template: '$1' },
	LRD: { code: 'LRD', decimal: '.', thousand: ',', fraction: 2, numericCode: '430', grapheme: '$', template: '$1' },
	LSL: { code: 'LSL', decimal: '.', thousand: ',', fraction: 2, numericCode: '426', grapheme: 'L', template: '$1' },
	LYD: { code: 'LYD', decimal: '.', thousand: ',', fraction: 3, numericCode: '434', grapheme: '.د.ل', template: '1 $' },
	MAD: { code: 'MAD', decimal: '.', thousand: ',', fraction: 2, numericCode: '504', grapheme: '.د.م', template: '1 $' },
	MDL: { code: 'MDL', decimal: '.', thousand: ',', fraction: 2, numericCode: '498', grapheme: 'lei', template: '1 $' },
	MGA: { code: 'MGA', decimal: '.', thousand: ',', fraction: 2, numericCode: '969', grapheme: 'Ar', template: '1$' },
	MKD: { code: 'MKD', decimal: '.', thousand: ',', fraction: 2, numericCode: '807', grapheme: 'ден', template: '$1' },
	MMK: { code: 'MMK', decimal: '.', thousand: ',', fraction: 2, numericCode: '104', grapheme: 'K', template: '$1' },
	MNT: { code: 'MNT', decimal: '.', thousand: ',', fraction: 2, numericCode: '496', grapheme: '₮', template: '$1' },
	MOP: { code: 'MOP', decimal: '.', thousand: ',', fraction: 2, numericCode: '446', grapheme: 'P', template: '1 $' },
	MRU: { code: 'MRU', decimal: '.', thousand: ',', fraction: 2, numericCode: '929', grapheme: 'UM', template: '$1' },
	MUR: { code: 'MUR', decimal: '.', thousand: ',', fraction: 2, numericCode: '480', grapheme: '₨', template: '$1' },
	MVR: { code: 'MVR', decimal: '.', thousand: ',', fraction: 2, numericCode: '462', grapheme: 'MVR', template: '1 $' },
	MWK: { code: 'MWK', decimal: '.', thousand: ',', fraction: 2, numericCode: '454', grapheme: 'MK', template: '$1' },
	MXN: { code: 'MXN', decimal: '.', thousand: ',', fraction: 2, numericCode: '484', grapheme: '$', template: '$1' },
	MXV: { code: 'MXV', decimal: '.', thousand: ',', fraction: 2, numericCode: '979', grapheme: 'MXV', template: '1 $' },
	MYR: { code: 'MYR', decimal: '.', thousand: ',', fraction: 2, numericCode: '458', grapheme: 'RM', template: '$1' },
	MZN: { code: 'MZN', decimal: '.', thousand: ',', fraction: 2, numericCode: '943', grapheme: 'MT', template: '$1' },
	NAD: { code: 'NAD', decimal: '.', thousand: ',', fraction: 2, numericCode: '516', grapheme: '$', template: '$1' },
	NGN: { code: 'NGN', decimal: '.', thousand: ',', fraction: 2, numericCode: '566', grapheme: '₦', template: '$1' },
	NIO: { code: 'NIO', decimal: '.', thousand: ',', fraction: 2, numericCode: '558', grapheme: 'C$', template: '$1' },
	NOK: { code: 'NOK', decimal: '.', thousand: ',', fraction: 2, numericCode: '578', grapheme: 'kr', template: '1 $' },
	NPR: { code: 'NPR', decimal: '.', thousand: ',', fraction: 2, numericCode: '524', grapheme: '₨', template: '$1' },
	NZD: { code: 'NZD', decimal: '.', thousand: ',', fraction: 2, numericCode: '554', grapheme: '$', template: '$1' },
	OMR: { code: 'OMR', decimal: '.', thousand: ',', fraction: 3, numericCode: '512', grapheme: '﷼', template: '1 $' },
	PAB: { code: 'PAB', decimal: '.', thousand: ',', fraction: 2, numericCode: '590', grapheme: 'B/.', template: '$1' },
	PEN: { code: 'PEN', decimal: '.', thousand: ',', fraction: 2, numericCode: '604', grapheme: 'S/', template: '$1' },
	PGK: { code: 'PGK', decimal: '.', thousand: ',', fraction: 2, numericCode: '598', grapheme: 'K', template: '1 $' },
	PHP: { code: 'PHP', decimal: '.', thousand: ',', fraction: 2, numericCode: '608', grapheme: '₱', template: '$1' },
	PKR: { code: 'PKR', decimal: '.', thousand: ',', fraction: 2, numericCode: '586', grapheme: '₨', template: '$1' },
	PLN: { code: 'PLN', decimal: '.', thousand: ',', fraction: 2, numericCode: '985', grapheme: 'zł', template: '1 $' },
	PYG: { code: 'PYG', decimal: '.', thousand: ',', fraction: 0, numericCode: '600', grapheme: 'Gs', template: '1$' },
	QAR: { code: 'QAR', decimal: '.', thousand: ',', fraction: 2, numericCode: '634', grapheme: '﷼', template: '1 $' },
	RON: { code: 'RON', decimal: '.', thousand: ',', fraction: 2, numericCode: '946', grapheme: 'lei', template: '$1' },
	RSD: { code: 'RSD', decimal: '.', thousand: ',', fraction: 2, numericCode: '941', grapheme: 'Дин.', template: '$1' },
	RUB: { code: 'RUB', decimal: '.', thousand: ',', fraction: 2, numericCode: '643', grapheme: '₽', template: '1 $' },
	RWF: { code: 'RWF', decimal: '.', thousand: ',', fraction: 0, numericCode: '646', grapheme: 'FRw', template: '1 $' },
	SAR: { code: 'SAR', decimal: '.', thousand: ',', fraction: 2, numericCode: '682', grapheme: '﷼', template: '1 $' },
	SBD: { code: 'SBD', decimal: '.', thousand: ',', fraction: 2, numericCode: '090', grapheme: '$', template: '$1' },
	SCR: { code: 'SCR', decimal: '.', thousand: ',', fraction: 2, numericCode: '690', grapheme: '₨', template: '$1' },
	SDG: { code: 'SDG', decimal: '.', thousand: ',', fraction: 2, numericCode: '938', grapheme: '£', template: '$1' },
	SEK: { code: 'SEK', decimal: '.', thousand: ',', fraction: 2, numericCode: '752', grapheme: 'kr', template: '1 $' },
	SGD: { code: 'SGD', decimal: '.', thousand: ',', fraction: 2, numericCode: '702', grapheme: 'S$', template: '$1' },
	SHP: { code: 'SHP', decimal: '.', thousand: ',', fraction: 2, numericCode: '654', grapheme: '£', template: '$1' },
	SLE: { code: 'SLE', decimal: '.', thousand: ',', fraction: 2, numericCode: '925', grapheme: 'Le', template: '1 $' },
	SLL: { code: 'SLL', decimal: '.', thousand: ',', fraction: 2, numericCode: '694', grapheme: 'Le', template: '1 $' },
	SOS: { code: 'SOS', decimal: '.', thousand: ',', fraction: 2, numericCode: '706', grapheme: 'Sh', template: '1 $' },
	SRD: { code: 'SRD', decimal: '.', thousand: ',', fraction: 2, numericCode: '968', grapheme: '$', template: '$1' },
	SSP: { code: 'SSP', decimal: '.', thousand: ',', fraction: 2, numericCode: '728', grapheme: '£', template: '1 $' },
	STN: { code: 'STN', decimal: '.', thousand: ',', fraction: 2, numericCode: '930', grapheme: 'Db', template: '1 $' },
	SVC: { code: 'SVC', decimal: '.', thousand: ',', fraction: 2, numericCode: '222', grapheme: '₡', template: '$1' },
	SYP: { code: 'SYP', decimal: '.', thousand: ',', fraction: 2, numericCode: '760', grapheme: '£', template: '1 $' },
	SZL: { code: 'SZL', decimal: '.', thousand: ',', fraction: 2, numericCode: '748', grapheme: '£', template: '$1' },
	THB: { code: 'THB', decimal: '.', thousand: ',', fraction: 2, numericCode: '764', grapheme: '฿', template: '$1' },
	TJS: { code: 'TJS', decimal: '.', thousand: ',', fraction: 2, numericCode: '972', grapheme: 'SM', template: '1 $' },
	TMT: { code: 'TMT', decimal: '.', thousand: ',', fraction: 2, numericCode: '934', grapheme: 'T', template: '1 $' },
	TND: { code: 'TND', decimal: '.', thousand: ',', fraction: 3, numericCode: '788', grapheme: '.د.ت', template: '1 $' },
	TOP: { code: 'TOP', decimal: '.', thousand: ',', fraction: 2, numericCode: '776', grapheme: 'T$', template: '$1' },
	TRY: { code: 'TRY', decimal: '.', thousand: ',', fraction: 2, numericCode: '949', grapheme: '₺', template: '$1' },
	TTD: { code: 'TTD', decimal: '.', thousand: ',', fraction: 2, numericCode: '780', grapheme: 'TT$', template: '$1' },
	TWD: { code: 'TWD', decimal: '.', thousand: ',', fraction: 2, numericCode: '901', grapheme: 'NT$', template: '$1' },
	TZS: { code: 'TZS', decimal: '.', thousand: ',', fraction: 2, numericCode: '834', grapheme: 'TSh', template: '$1' },
	UAH: { code: 'UAH', decimal: '.', thousand: ',', fraction: 2, numericCode: '980', grapheme: '₴', template: '1 $' },
	UGX: { code: 'UGX', decimal: '.', thousand: ',', fraction: 0, numericCode: '800', grapheme: 'USh', template: '1 $' },
	USD: { code: 'USD', decimal: '.', thousand: ',', fraction: 2, numericCode: '840', grapheme: '$', template: '$1' },
	USN: { code: 'USN', decimal: '.', thousand: ',', fraction: 2, numericCode: '997', grapheme: 'US$', template: '$1' },
	UYI: { code: 'UYI', decimal: '.', thousand: ',', fraction: 0, numericCode: '940', grapheme: 'UYI', template: '1 $' },
	UYU: { code: 'UYU', decimal: '.', thousand: ',', fraction: 2, numericCode: '858', grapheme: '$U', template: '$1' },
	UYW: { code: 'UYW', decimal: '.', thousand: ',', fraction: 4, numericCode: '927', grapheme: 'UYW', template: '1 $' },
	UZS: { code: 'UZS', decimal: '.', thousand: ',', fraction: 2, numericCode: '860', grapheme: 'so’m', template: '$1' },
	VES: { code: 'VES', decimal: '.', thousand: ',', fraction: 2, numericCode: '928', grapheme: 'Bs.S', template: '$1' },
	VND: { code: 'VND', decimal: '.', thousand: ',', fraction: 0, numericCode: '704', grapheme: '₫', template: '1 $' },
	VUV: { code: 'VUV', decimal: '.', thousand: ',', fraction: 0, numericCode: '548', grapheme: 'Vt', template: '$1' },
	WST: { code: 'WST', decimal: '.', thousand: ',', fraction: 2, numericCode: '882', grapheme: 'T', template: '1 $' },
	XAF: { code: 'XAF', decimal: '.', thousand: ',', fraction: 0, numericCode: '950', grapheme: 'Fr', template: '1 $' },
	XAG: { code: 'XAG', decimal: '.', thousand: ',', fraction: 0, numericCode: '961', grapheme: 'oz t', template: '1 $' },
	XAU: { code: 'XAU', decimal: '.', thousand: ',', fraction: 0, numericCode: '959', grapheme: 'oz t', template: '1 $' },
	XBA: { code: 'XBA', decimal: '.', thousand: ',', fraction: 0, numericCode: '955', grapheme: 'XBA', template: '1 $' },
	XBB: { code: 'XBB', decimal: '.', thousand: ',', fraction: 0, numericCode: '956', grapheme: 'XBB', template: '1 $' },
	XBC: { code: 'XBC', decimal: '.', thousand: ',', fraction: 0, numericCode: '957', grapheme: 'XBC', template: '1 $' },
	XBD: { code: 'XBD', decimal: '.', thousand: ',', fraction: 0, numericCode: '958', grapheme: 'XBD', template: '1 $' },
	XCD: { code: 'XCD', decimal: '.', thousand: ',', fraction: 2, numericCode: '951', grapheme: '$', template: '$1' },
	XDR: { code: 'XDR', decimal: '.', thousand: ',', fraction: 0, numericCode: '960', grapheme: 'SDR', template: '1 $' },
	XOF: { code: 'XOF', decimal: '.', thousand: ',', fraction: 0, numericCode: '952', grapheme: 'CFA', template: '1 $' },
	XPD: { code: 'XPD', decimal: '.', thousand: ',', fraction: 0, numericCode: '964', grapheme: 'oz t', template: '1 $' },
	XPF: { code: 'XPF', decimal: '.', thousand: ',', fraction: 0, numericCode: '953', grapheme: 'CFP', template: '1 $' },
	XPT: { code: 'XPT', decimal: '.', thousand: ',', fraction: 0, numericCode: '962', grapheme: 'oz t', template: '1 $' },
	XSU: { code: 'XSU', decimal: '.', thousand: ',', fraction: 0, numericCode: '994', grapheme: 'XSU', template: '1 $' },
	XTS: { code: 'XTS', decimal: '.', thousand: ',', fraction: 0, numericCode: '963', grapheme: 'XTS', template: '1 $' },
	XUA: { code: 'XUA', decimal: '.', thousand: ',', fraction: 0, numericCode: '965', grapheme: 'XUA', template: '1 $' },
	XXX: { code: 'XXX', decimal: '.', thousand: ',', fraction: 0, numericCode: '999', grapheme: 'XXX', template: '1 $' },
	YER: { code: 'YER', decimal: '.', thousand: ',', fraction: 2, numericCode: '886', grapheme: '﷼', template: '1 $' },
	ZAR: { code: 'ZAR', decimal: '.', thousand: ',', fraction: 2, numericCode: '710', grapheme: 'R', template: '$1' },
	ZMW: { code: 'ZMW', decimal: '.', thousand: ',', fraction: 2, numericCode: '967', grapheme: 'ZK', template: '$1' },
	ZWL: { code: 'ZWL', decimal: '.', thousand: ',', fraction: 2, numericCode: '932', grapheme: 'Z$', template: '$1' },
} as const satisfies Record<CurrencyCode, CurrencyDefinitionData>;
